# Site settings
title: Shadowfacts
subtitle: The outer part of a shadow is called the penumbra
email: me@shadowfacts.net
description: Just my various ramblings.
baseurl: 
url: https://shadowfacts.net
enforce_ssl: shadowfacts.net
twitter_username: ShadowfactsDev
github_username:  shadowfacts

# Build settings
markdown: kramdown

permalink: /:categories/:year/:month/:day/:title/

plugins: [jekyll-paginate]
paginate: 5

collections:
  series:
    permalink: /tutorials/:path/
    output: true
  tutorials:
    permalink: /tutorials/:path/
    output: true